console.log('1' == 1)
console.log('1' === 1)
console.log('1' != 1)
console.log('1' !== 1)
console.log('1' < 1)
console.log('1' > 1)
console.log('1' <= 1)
console.log('1' >= 1)
console.log(new Date(0) == new Date(0))
console.log(new Date(0) === new Date(0))
console.log(new Date(0).getTime == new Date(0).getTime)
console.log(new Date(0).getTime === new Date(0).getTime)
console.log(undefined == null)
console.log(undefined === null)